version: '3'

services:

  app:
    build: nc-image
    restart: always
    volumes:
      - ${DATA_DIR}/next-cloud:/var/www/html
      - ${CERTS_DIR}/${NEXT_CLOUD_HOSTNAME}/fullchain.pem:/certs/fullchain.pem:ro
      - ${CERTS_DIR}/${NEXT_CLOUD_HOSTNAME}/privkey.pem:/certs/privkey.pem:ro
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=db
      - NEXT_CLOUD_HOSTNAME=${NEXT_CLOUD_HOSTNAME}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db

  db:
    image: postgres:12.2
    restart: always
    volumes:
      - ${DATA_DIR}/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}

